kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker:linux-arm64
  settings:
    repo: h3rj4n/hass
    tags:
      - latest
      - '0.101'
      - '0.101.2'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image: docker:latest
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker service update -q --image h3rj4n/hass:latest hass_hass


volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
