kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker:linux-arm64
  settings:
    repo: h3rj4n/hass
    tags:
      - latest
      - '0.86.1'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
