kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    repo: h3rj4n/hass
    dry-run: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
